# Site settings
title: cobbr.io
# email: none
description: > # this means to ignore newlines until "baseurl:"
  cobbr.io is the personal blog of Ryan Cobb
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cobbr.io"
twitter_username: cobbr_io
github_username:  cobbr

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

