# Site settings
title: cobbr.io
# email: none
# description: Ryan Cobb
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cobbr.io"
twitter_username: cobbr_io
github_username:  cobbr
permalink: /:title.html

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

