# Site settings
title: cobbr.github.io
# email: none yet :(
description: > # this means to ignore newlines until "baseurl:"
  cobbr.github.io is the personal blog of Ryan Cobb
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cobbr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cobbr_io
github_username:  cobbr

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

